- name: BASIC DESTROY
  hosts: 
    - local
  become: yes


  tasks:

  - name: Terminate Basic
    shell:
      cmd: sh /opt/simple/basic/etc/docker-destroy.sh

  - name: Remove Basic
    shell:
      cmd: rm -rf /opt/simple/basic
