version: '3.8'

services:

  web_blue:
    build: /opt/simple/frontend/etc/web_blue
    image: web_blue
    restart: always
    ports:
      - '80'
    volumes:
      - /opt/simple/frontend/var:/var/www/html

  web_green:
    build: /opt/simple/frontend/etc/web_green
    image: web_green
    restart: always
    ports:
      - '80'
    volumes:
      - /opt/simple/frontend/var:/var/www/html

  web_lb:
    image: dockercloud/haproxy
    restart: always
    ports:
      - '80:80'
    links:
      - web_blue
      - web_green
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

